"""
Simple email format schema for the emailer agent output.
"""

from typing import Optional
from pydantic import BaseModel, Field


class EmailResponse(BaseModel):
    """Schema for promotional email generated by ProductEmailerAgent."""

    subject: str = Field(..., description="Email subject line")
    body: str = Field(..., description="Complete email body content")

    recipient_name: str = Field(..., description="Name of the email recipient")
    product_name: str = Field(..., description="Product being promoted")
    organization_name: Optional[str] = Field(
        None, description="Recipient's organization"
    )

    success: bool = Field(
        default=True, description="Whether email generation was successful"
    )
    error_message: Optional[str] = Field(
        None, description="Error message if generation failed"
    )
